### ISSUE TITLE
启动的报这个错，好象是那个异步数据仓库加载初始化的时候报错！请问是什么原因？

### ISSUE THREAD

**Issue by 5432935** [SwingFrog/Summer#4]
Summer Server Powered by Toke 2018

----------------------------------------------------------------------------------------------------------------------------- 
2019-10-23 17:55:03:272 [main] INFO [] summer init... 
2019-10-23 17:55:03:272 [main] INFO [] config load... 
2019-10-23 17:55:03:382 [main] ERROR [] null 
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.swingfrog.summer.config.ConfigUtil.getValueByTypeAndString(ConfigUtil.java:49)
	at com.swingfrog.summer.config.ConfigUtil.loadDataWithBean(ConfigUtil.java:34)
	at com.swingfrog.summer.db.repository.AsyncCacheRepositoryMgr.loadConfig(AsyncCacheRepositoryMgr.java:41)
	at com.swingfrog.summer.app.Summer.hot(Summer.java:90)
	at com.test.summerDemo.game.GameApp.main(GameApp.java:29)
2019-10-23 17:55:03:397 [main] INFO [] async cache repository manager loading config, core thread num[16] 
2019-10-23 17:55:03:397 [main] INFO [] task init 
2019-10-23 17:55:03:444 [main] INFO [] container init... 
2019-10-23 17:55:03:460 [main] INFO [] register remote ChatRemote 
2019-10-23 17:55:03:460 [main] INFO [] server init...

**Comment by SwingFrog** [comment]
db.properties少了个字段
asyncCache.coreThread=0

**Comment by 5432935** [comment]
感谢！
